version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-ansible
    restart: always
    deploy:
      replicas: 5

networks:
  default:
    external:
      name: docker_ansible


  